(run-stack-machine
	(make-stack-machine 
		empty-stack 
		#hash((0 . None) (1 . None) (2 . None) (3 . None))
		#hash((0 . 0) (1 . 0) (2 . 10) (3 . 5) (4 . 2))
		#hash((0 . "range"))
		'((LOAD_CONST . 1) (STORE_FAST . 0) (SETUP_LOOP . 24) (LOAD_GLOBAL . 0) (LOAD_CONST . 2) (CALL_FUNCTION . 1) (GET_ITER . 0) (FOR_ITER . 12) (STORE_FAST . 1) (LOAD_FAST . 0) (LOAD_FAST . 1) (INPLACE_ADD . 0) (STORE_FAST . 0) (JUMP_ABSOLUTE . 14) (POP_BLOCK . 0) (SETUP_LOOP . 24) (LOAD_GLOBAL . 0) (LOAD_CONST . 3) (CALL_FUNCTION . 1) (GET_ITER . 0) (FOR_ITER . 12) (STORE_FAST . 2) (LOAD_FAST . 0) (LOAD_FAST . 1) (INPLACE_SUBTRACT . 0) (STORE_FAST . 0) (JUMP_ABSOLUTE . 40) (POP_BLOCK . 0) (SETUP_LOOP . 36) (LOAD_GLOBAL . 0) (LOAD_CONST . 2) (CALL_FUNCTION . 1) (GET_ITER . 0) (FOR_ITER . 24) (STORE_FAST . 3) (LOAD_FAST . 3) (LOAD_CONST . 4) (BINARY_MODULO . 0) (LOAD_CONST . 1) (COMPARE_OP . 2) (POP_JUMP_IF_FALSE . 66) (LOAD_FAST . 0) (LOAD_FAST . 3) (INPLACE_ADD . 0) (STORE_FAST . 0) (JUMP_ABSOLUTE . 66) (POP_BLOCK . 0) (LOAD_CONST . 0) (RETURN_VALUE . 0))
		0))