(run-stack-machine
	(make-stack-machine 
		empty-stack 
		#hash((0 . None) (1 . None) (2 . None) (3 . None) (4 . None) (5 . None))
		#hash((0 . 0) (1 . 5) (2 . 7) (3 . 20) (4 . 10) (5 . 2) (6 . 0) (7 . 3))
		#hash()
		'((LOAD_CONST . 1) (STORE_FAST . 0) (LOAD_CONST . 2) (STORE_FAST . 1) (LOAD_FAST . 0) (LOAD_FAST . 1) (COMPARE_OP . 4) (POP_JUMP_IF_FALSE . 24) (LOAD_FAST . 0) (STORE_FAST . 1) (LOAD_CONST . 3) (STORE_FAST . 2) (LOAD_FAST . 0) (LOAD_FAST . 1) (COMPARE_OP . 0) (POP_JUMP_IF_FALSE . 40) (LOAD_FAST . 0) (STORE_FAST . 1) (LOAD_CONST . 4) (STORE_FAST . 2) (LOAD_FAST . 0) (LOAD_FAST . 1) (BINARY_ADD . 0) (STORE_FAST . 3) (LOAD_FAST . 3) (LOAD_CONST . 1) (INPLACE_ADD . 0) (STORE_FAST . 3) (LOAD_FAST . 3) (LOAD_CONST . 5) (BINARY_MODULO . 0) (LOAD_CONST . 6) (COMPARE_OP . 2) (POP_JUMP_IF_FALSE . 76) (LOAD_FAST . 3) (LOAD_CONST . 7) (INPLACE_SUBTRACT . 0) (STORE_FAST . 3) (LOAD_FAST . 3) (LOAD_CONST . 5) (BINARY_MODULO . 0) (LOAD_CONST . 6) (COMPARE_OP . 3) (POP_JUMP_IF_FALSE . 96) (LOAD_FAST . 3) (LOAD_CONST . 7) (INPLACE_MODULO . 0) (STORE_FAST . 3) (LOAD_FAST . 2) (LOAD_FAST . 3) (BINARY_ADD . 0) (STORE_FAST . 4) (LOAD_FAST . 0) (LOAD_FAST . 1) (BINARY_ADD . 0) (STORE_FAST . 5) (LOAD_FAST . 4) (LOAD_FAST . 5) (COMPARE_OP . 4) (POP_JUMP_IF_FALSE . 124) (LOAD_FAST . 4) (STORE_FAST . 5) (LOAD_CONST . 0) (RETURN_VALUE . 0))
		0))