(run-stack-machine
	(make-stack-machine 
		empty-stack 
		#hash((0 . None) (1 . None) (2 . None))
		#hash((0 . 0) (1 . 10) (2 . 0) (3 . 1) (4 . 2))
		#hash()
		'((LOAD_CONST . 1) (STORE_FAST . 0) (LOAD_CONST . 2) (STORE_FAST . 1) (LOAD_CONST . 2) (STORE_FAST . 2) (SETUP_LOOP . 36) (LOAD_FAST . 0) (LOAD_FAST . 1) (COMPARE_OP . 3) (POP_JUMP_IF_FALSE . 48) (LOAD_FAST . 0) (LOAD_CONST . 3) (INPLACE_SUBTRACT . 0) (STORE_FAST . 0) (LOAD_FAST . 1) (LOAD_CONST . 3) (INPLACE_ADD . 0) (STORE_FAST . 1) (LOAD_FAST . 2) (LOAD_CONST . 4) (INPLACE_ADD . 0) (STORE_FAST . 2) (JUMP_ABSOLUTE . 14) (POP_BLOCK . 0) (LOAD_CONST . 2) (STORE_FAST . 0) (LOAD_CONST . 1) (STORE_FAST . 1) (SETUP_LOOP . 36) (LOAD_FAST . 0) (LOAD_FAST . 1) (COMPARE_OP . 0) (POP_JUMP_IF_FALSE . 94) (LOAD_FAST . 0) (LOAD_CONST . 3) (INPLACE_ADD . 0) (STORE_FAST . 0) (LOAD_FAST . 1) (LOAD_CONST . 3) (INPLACE_SUBTRACT . 0) (STORE_FAST . 1) (LOAD_FAST . 2) (LOAD_CONST . 4) (INPLACE_ADD . 0) (STORE_FAST . 2) (JUMP_ABSOLUTE . 60) (POP_BLOCK . 0) (LOAD_CONST . 0) (RETURN_VALUE . 0))
		0))