(run-stack-machine
	(make-stack-machine 
		empty-stack 
		#hash((0 . None) (1 . None) (2 . None) (3 . None) (4 . None) (5 . None))
		#hash((0 . 0) (1 . 3) (2 . 1) (3 . 2) (4 . 0) (5 . 10) (6 . (1 2 3)) (7 . (3 2 1)) (8 . (1 2 3)))
		#hash()
		'((LOAD_CONST . 1) (STORE_FAST . 0) (SETUP_LOOP . 38) (LOAD_CONST . 6) (GET_ITER . 0) (FOR_ITER . 30) (STORE_FAST . 1) (SETUP_LOOP . 24) (LOAD_CONST . 7) (GET_ITER . 0) (FOR_ITER . 16) (STORE_FAST . 2) (LOAD_FAST . 0) (LOAD_FAST . 1) (LOAD_FAST . 2) (BINARY_ADD . 0) (INPLACE_ADD . 0) (STORE_FAST . 0) (JUMP_ABSOLUTE . 20) (POP_BLOCK . 0) (JUMP_ABSOLUTE . 10) (POP_BLOCK . 0) (LOAD_CONST . 4) (STORE_FAST . 3) (LOAD_CONST . 5) (STORE_FAST . 4) (LOAD_CONST . 4) (STORE_FAST . 5) (SETUP_LOOP . 58) (LOAD_FAST . 3) (LOAD_FAST . 4) (COMPARE_OP . 3) (POP_JUMP_IF_FALSE . 114) (LOAD_FAST . 3) (LOAD_CONST . 2) (INPLACE_ADD . 0) (STORE_FAST . 3) (LOAD_FAST . 4) (LOAD_CONST . 2) (INPLACE_SUBTRACT . 0) (STORE_FAST . 4) (SETUP_LOOP . 28) (LOAD_CONST . 8) (GET_ITER . 0) (FOR_ITER . 20) (STORE_FAST . 1) (LOAD_FAST . 3) (LOAD_FAST . 4) (BINARY_ADD . 0) (STORE_FAST . 5) (LOAD_FAST . 5) (LOAD_FAST . 1) (INPLACE_ADD . 0) (STORE_FAST . 5) (JUMP_ABSOLUTE . 88) (POP_BLOCK . 0) (JUMP_ABSOLUTE . 58) (POP_BLOCK . 0) (LOAD_CONST . 0) (RETURN_VALUE . 0))
		0))